// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKnmrDtqRUeVEnUdZ-IgNsDokqcdbdTZs',
    appId: '1:885559779394:web:fc759c2ecbb7ce09810ddb',
    messagingSenderId: '885559779394',
    projectId: 'tds-money',
    authDomain: 'tds-money.firebaseapp.com',
    storageBucket: 'tds-money.appspot.com',
    measurementId: 'G-67D90ZTJ1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDboYrKgjmVH0pw5wkvuof0NM6YotyFXc',
    appId: '1:885559779394:android:70250bb4f77e1519810ddb',
    messagingSenderId: '885559779394',
    projectId: 'tds-money',
    storageBucket: 'tds-money.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCah_MkUW_aeDTCfyHua4mxpGl7X7xsHgU',
    appId: '1:885559779394:ios:d52753f26465923c810ddb',
    messagingSenderId: '885559779394',
    projectId: 'tds-money',
    storageBucket: 'tds-money.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCah_MkUW_aeDTCfyHua4mxpGl7X7xsHgU',
    appId: '1:885559779394:ios:2d4a3cf215fd6ed3810ddb',
    messagingSenderId: '885559779394',
    projectId: 'tds-money',
    storageBucket: 'tds-money.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
